Feat implement send sms kotlin
appwrite/demos-for-functions pull request #100
Opened 2021-10-01 07:19 UTC by Rishavgupta12345

send SMS () function implemented successfully , using twilio library as mentioned in the issue #92

2021-10-04 08:13 UTC, Meldiron requested changes
Great PR! 🤯 Left some comments during the review, please check them out.

Feel free to refer to other PRs on the same [issues](https://github.com/appwrite/demos-for-functions/issues/92) (in different languages) to see how they implemented this function. That will answer most questions you might have about my comments.

If you still have some questions, please ask and I will explain.

2021-10-04 08:13 UTC, Meldiron commented on kotlin/send_sms/sendSMS.kt
> +fun sendSMS(args:Array<String>)
I am not 100% sure this will execute automatically, have you tested?

If it doesn't work, we might need some `main` function, checkout other examples at https://github.com/appwrite/demos-for-functions/tree/master/kotlin

2021-10-04 08:13 UTC, Meldiron commented on kotlin/send_sms/readme.md
> +IT is the sendSMS function .
Please make readme more descriptive. Take a look at others readmes in our repo and use it as a template for yours: https://github.com/appwrite/demos-for-functions/tree/master/kotlin/welcome-email

2021-10-04 08:13 UTC, Meldiron commented on kotlin/send_sms/sendSMS.kt
> +    Twilio.init(java.lang.System.getenv(name:"TWILIO_ACCOUNT_STD"),System.getenv(name:"TWILIO_AUTH_TOKEN"))
Please put all authentification related variables into environment variables.

2021-10-04 08:13 UTC, Meldiron commented on kotlin/send_sms/sendSMS.kt
> +        body:"hi its my first sms in kotlin"
Please get all dynamic data from `APPWRITE_FUNCTION_DATA`. As we have multiple data, we can use json for input.

2021-10-31 13:47 UTC, christyjacob4 commented
@Rishavgupta12345 let us know if you're still working on this. Else we'll need to close this

2021-11-17 07:33 UTC, christyjacob4 commented
@Rishavgupta12345 closing this PR since there has been no activity on this. Feel free to re open this if you feel like working on it again 👍

2021-11-17 07:33 UTC, closed without merging