Implement generate bitly url JS
appwrite/demos-for-functions pull request #105
Opened 2021-10-01 12:14 UTC by arshxyz

Demo function to generate bit.ly shortened URL in JS

References #82

2021-10-04 06:23 UTC, Meldiron requested changes
Great job, we just need to do a few small changes 😊

2021-10-04 06:23 UTC, Meldiron commented on nodejs/generate-bitly-url/index.js
> +const payload = JSON.parse(process.env.APPWRITE_FUNCTION_DATA);
No reason to use JSON as we only get 1 input and it's `url`. The input can simply be `string` holding our `url`. Please also document this in `README.md` so users know they need to provide this input and how.

2021-10-04 06:23 UTC, Meldiron commented on nodejs/generate-bitly-url/index.js
> +    console.log(response.data.link);
Please document this in `README.md`so users know what to expect.

2021-10-04 06:23 UTC, Meldiron commented on nodejs/generate-bitly-url/index.js
> +    console.log(error);
If we get an error, we need to use `console.error()` so the error is sent in the `stderr` and we can find out if the function was a success or not when fetching function status on frontend.

2021-10-04 19:15 UTC, arshxyz commented
@Meldiron Hi, I've made the required changes. Thanks for the review!

2021-10-30 08:03 UTC, Meldiron approved these changes
Looks good to me!

2021-10-30 08:04 UTC, Meldiron commented
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

2021-10-30 08:04 UTC, merged