Feat implement generate bitly url dart
appwrite/demos-for-functions pull request #106
Opened 2021-10-01 13:03 UTC by DonnC

shorten long url with dart cloud function
#82

2021-10-04 07:16 UTC, Meldiron requested changes
Great PR! 🤯 Left some comments during the review, please check them out.

I went through your other PR first, check that one out too, some mistakes are the same in both PRs. There, I explained everything in detail.

I noticed that this PR also includes python files, please remove them from this PR.

Also please:
- Rename folder from `feat-implement-generate-bitly-url-dart` to `generate-bitly-url`
- Rename `shots` to `docs-images`
- Remove `tar.gz` file from PR

2021-10-04 07:16 UTC, Meldiron commented on dart/feat-implement-generate-bitly-url-dart/pubspec.yaml
> +name: feat_implement_generate_bitly_url_dart
Please rename to `generate_bitly_url`

2021-10-04 07:16 UTC, Meldiron commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +To setup dart cloud function, follow this excellent tutorial [on dev here](https://dev.to/appwrite/learn-how-to-create-and-run-appwrite-functions-with-dart-5668)
`To setup dart cloud function, follow [this excellent tutorial on Dev.to](https://dev.to/appwrite/learn-how-to-create-and-run-appwrite-functions-with-dart-5668)

2021-10-04 07:16 UTC, Meldiron commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +* **LONG_URL** - example long url to shorten
Do we use this `LONG_URL` in the code? I cannot find it.

2021-10-04 07:16 UTC, Meldiron commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +You can use both the `APPWRITE_FUNCTION_DATA` or `APPWRITE_FUNCTION_EVENT_DATA` default environment variables too depending on your use-case.<br>
Can you use `APPWRITE_FUNCTION_EVENT_DATA`? I cant see it in the code. It would be awesome to implement this, tho... Just get both variables, check which one exists and use it. Please check if this would be possible.

2021-10-04 07:16 UTC, Meldiron commented on dart/feat-implement-generate-bitly-url-dart/main.dart
> +  final payload = jsonDecode(envVars['APPWRITE_FUNCTION_DATA']!);
Let's not use JSONs in this function, we need simple string as input and simple string as output.

2021-10-04 07:23 UTC, Meldiron commented
@lohanidamodar Please check the code

2021-10-04 07:24 UTC, DonnC commented
yes i have also considered applying all those fixes to all my `PRs` 😅
Thanks for that, i will be adding those changes today

2021-10-04 08:36 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +You can use both the `APPWRITE_FUNCTION_DATA` or `APPWRITE_FUNCTION_EVENT_DATA` default environment variables too depending on your use-case.<br>
`APPWRITE_FUNCTION_EVENT_DATA` is depricated.

2021-10-04 08:37 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/pubspec.yaml
> +name: feat_implement_generate_bitly_url_dart
Also rename the folder

2021-10-04 08:45 UTC, lohanidamodar requested changes
@DonnC great job on dart functions. Some small changes. Also I believe it's best to keep python and dart example on separate PR.

2021-10-04 08:45 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +A dart Cloud Function for generating a bitly short link from a passed long url link.
```suggestion
A dart Cloud Function for generating a bitly short link from a given url.
```

2021-10-04 08:45 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +<br>
```suggestion
```

2021-10-04 08:45 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +* **LONG_URL** - example long url to shorten
We don't need this.

2021-10-04 08:45 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +{
Let's use simple string instead.

2021-10-04 08:45 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/README.md
> +You can use any event here to enable automatic configuring of this cloud function, just make sure that the payload contains the `url` field so that the function will pick it up as the field containin
For this we don't need the trigger. Our triggers don't support custom field, so this will not be possible.

2021-10-04 08:45 UTC, lohanidamodar commented on dart/feat-implement-generate-bitly-url-dart/pubspec.yaml
> +  path: ^1.8.0
```suggestion
```
We are not using this. We can remove.

2021-10-05 07:36 UTC, lohanidamodar commented
@DonnC apart from small changes dart one looks good to me. Also @DonnC I again emphasize to put the Python function on a separate PR and remove from this one. Thank you.

2021-10-05 07:55 UTC, DonnC commented
> @DonnC apart from small changes dart one looks good to me. Also @DonnC I again emphasize to put the Python function on a separate PR and remove from this one. Thank you.

Thank you @lohanidamodar , i have seperated them.

2021-11-17 07:39 UTC, christyjacob4 commented
@DonnC  Please resolve the conflict and we're good to merge this 👍

2021-11-17 07:56 UTC, DonnC commented
> @DonnC Please resolve the conflict and we're good to merge this +1

Okay, it was changed by another maintainer, can you check again @christyjacob4

2021-11-17 08:02 UTC, christyjacob4 commented
@DonnC It still says there are conflicts that need to be resolved
<img width="777" alt="Screenshot 2021-11-17 at 12 01 52 PM" src="https://user-images.githubusercontent.com/20852629/142159627-063d3124-6f23-4e99-80a9-7768bffdcefc.png">

2021-11-17 08:04 UTC, DonnC commented
@lohanidamodar can you assist sir, im not sure whats the conflict about in my pubspec file

2021-11-23 05:01 UTC, closed without merging