Implementation of genrateUnsplashImage function in python
appwrite/demos-for-functions pull request #109
Opened 2021-10-01 18:58 UTC by avats-dev

Fixes #87 

Created generateUnsplashImage folder in python directory with `main.py`, `requirements.txt` and `README.md`.

Some things I would like to mention for reviewers:
- This function uses default `order-by` parameter which is `relevant`. Other value available for this is `latest`. See [this](https://unsplash.com/documentation#parameters-16) for further reference.
- This function returns `imageUrl` for downloading the image. Other options available for this is `HTML` and `self` as could be seen [here](https://unsplash.com/documentation#link-relations-1) for reference.
- I don't know what would trigger this and hence I have left trigger value as empty for now in the `README.md`.

Please review the PR and suggest edits. Thanks!

2021-10-04 07:22 UTC, Meldiron requested changes
Great PR! 🤯 Left some comments during the review, please check them out.

Also, please:
- Rename the folder to `generate-unsplash-image` to stay consistent with the rest of the repo

2021-10-04 07:22 UTC, Meldiron commented on python/generateUnsplashImage/README.md
> +## Trigger
Let's say that function needs to be triggered manually from Console or using `executeFunction` from our SDK.

2021-10-04 07:22 UTC, Meldiron commented on python/generateUnsplashImage/main.py
> +def getUnsplashImage(keyword):
I don't think this would work, did you run it successfully?

I think we need to execute this function and print it's response. To provide keyword, we can use env variable `APPWRITE_FUNCTION_DATA `

2021-10-04 07:22 UTC, Meldiron commented on python/generateUnsplashImage/main.py
> +    return imageUrl, imageAuthor
After executing the function and printing the results, let's make sure that the response is in JSON format. So the output should be something like: `{"imageUrl": "blabla", "imageAuthor": "blabla" }`

2021-10-04 07:22 UTC, Meldiron commented on python/generateUnsplashImage/main.py
> +        imageAuthor = "Could not search the keyword!"
If an error occurs, let's try to actually throw an error so it's stored in `stderr` in Appwrite. Not 100% sure how to this in python, another reviewer will give you a hint on this.

2021-10-04 07:22 UTC, Meldiron commented
@christyjacob4 please check the code. Take a closer look at handling errors.

2021-10-30 21:55 UTC, avats-dev commented
@Meldiron @christyjacob4 I have updated PR with all requested changes and screenshots after testing it. 
LMK if it needs any more tweaks. :tada:

2021-11-17 07:56 UTC, christyjacob4 approved these changes

2021-11-17 07:57 UTC, merged

2021-11-17 07:57 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)