Implementation of translateText function in python
appwrite/demos-for-functions pull request #110
Opened 2021-10-01 20:31 UTC by avats-dev

Fixes #97 

Created translateText folder in python directory with `main.py`, `requirements.txt` and `README.md`.

Some things I would like to mention for reviewers:
- This function uses environment variable for authentication without explicitly using it as per google translate docs. I'm not hundred percent sure about if they need the file path or the key as value. See [this](https://cloud.google.com/docs/authentication/getting-started) for reference.
- This function uses `sourceLanguage` as a function argument while it is not necessarily needed by google translate.
- I don't know what would trigger this and hence I have left trigger value as empty for now in the `README.md`.
- This function uses `six` module for `py2.x` and `py3.x` compatibility and this could be removed if `py>3.0` is asserted.
 
Please review the PR and suggest edits. Thanks!

2021-10-04 07:45 UTC, Meldiron requested changes
Great PR! 🤯 Left some comments during the review, please check them out.

I reviewed your other PR first, please check that one out first, some points might apply to this PR too.

2021-10-04 07:45 UTC, Meldiron commented on python/translateText/main.py
> +def translateText(text, sourceLanguage, destinationLanguage):
We need to execute the function and print the response. To get these dynamic input, we can use environment variable `APPWRITE_FUNCTION_DATA` (it's content can be a json that you can then parse and use. please document expected input in readme).

2021-10-04 07:45 UTC, Meldiron commented on python/translateText/main.py
> +    translateClient = translate.Client()
Yeah, I would be scared about not using some Google Cloud KEY or something.. Can we figure this one out? What does their permission keys file store? Is that a JSON? Can we just put it into the environment variable?

2021-10-04 07:45 UTC, Meldiron commented on python/translateText/README.md
> +* **GOOGLE_APPLICATION_CREDENTIALS** - Your google json API key path
Where do we use this variable? We surly need to authentificate.

2021-10-04 07:45 UTC, Meldiron commented on python/translateText/README.md
> +## Trigger
Let's say that trigger is manual so either manually from console or using `executeFunction` from SDK

2021-10-04 07:46 UTC, Meldiron commented
Also please rename folder from `translateText` to `translate-text` to be consistent with the rest of the repo

2021-10-31 00:40 UTC, avats-dev commented
@Meldiron I have updated the PR and tested it locally and also have attached screenshots for the same. Do let me know if you need any more tweaks. :tada:

2021-11-17 07:59 UTC, christyjacob4 approved these changes

2021-11-17 07:59 UTC, merged

2021-11-17 07:59 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)