Feat implement get internet speed dart
appwrite/demos-for-functions pull request #113
Opened 2021-10-02 07:41 UTC by GunjanDhanuka

:heavy_check_mark: Dart implementation of the getInternetSpeed function as mentioned in #89 . This function uses Speedtest CLI to check the download and upload speed of the server. The results are printed as the output of the function in the units of Mbps.

2021-10-03 05:22 UTC, lohanidamodar requested changes

2021-10-03 05:22 UTC, lohanidamodar commented on dart/getInternetSpeed/README.md
> +
Remove extra line
```suggestion
```

2021-10-03 05:22 UTC, lohanidamodar commented on dart/getInternetSpeed/README.md
> +$ dart pub get
need an step to update PUB_CACHE environment to make sure pub dependencies are kept in `.appwrite` folder and folder structure should contain `.appwrite/` folder. Check existing dart function demo.

2021-10-03 05:22 UTC, lohanidamodar commented on dart/getInternetSpeed/main.dart
> +// void main() {
Please remove if this is not necessary. Thank you.

2021-10-03 05:22 UTC, lohanidamodar commented on dart/getInternetSpeed/pubspec.yaml
> +  dart_appwrite: ^0.6.1
Is this package used anywhere?

2021-10-03 07:08 UTC, GunjanDhanuka commented on dart/getInternetSpeed/pubspec.yaml
> +  dart_appwrite: ^0.6.1
No it isn't. I have updated it! Thanks!

2021-10-03 07:08 UTC, GunjanDhanuka commented on dart/getInternetSpeed/main.dart
> +// void main() {
Done!

2021-10-03 07:09 UTC, GunjanDhanuka commented on dart/getInternetSpeed/README.md
> +$ dart pub get
Done! Thanks a lot! I am new to contributing too appwrite hence these details got missed :sweat_smile:

2021-10-03 07:11 UTC, GunjanDhanuka commented
> heavy_check_mark Dart implementation of the getInternetSpeed function as mentioned in #89 . This function uses Speedtest CLI to check the download and upload speed of the server. The results are printed as the output of the function in the units of Mbps.

I have made the corrections as suggested! Please review it

2021-10-04 06:52 UTC, lohanidamodar requested changes
@GunjanDhanuka please there is an unintended removal of `python/.gitkeep`, please fix it. Thank you

2021-10-04 07:47 UTC, Meldiron commented
Also, please rename the folder from `getInternetSpeed` to `get-internet-speed` to stay  consistent with the rest of the repo.

2021-10-05 07:18 UTC, GunjanDhanuka commented
> @GunjanDhanuka please there is an unintended removal of `python/.gitkeep`, please fix it. Thank you

That file was an empty file created since I mistakenly started working on Python implementation on the same branch. That is why I deleted that file. Do I still need to add that empty file?

2021-10-05 07:20 UTC, GunjanDhanuka commented
> Also, please rename the folder from `getInternetSpeed` to `get-internet-speed` to stay consistent with the rest of the repo.

Done! :+1:

2021-10-05 07:21 UTC, GunjanDhanuka commented
> > @GunjanDhanuka please there is an unintended removal of `python/.gitkeep`, please fix it. Thank you
> 
> That file was an empty file created since I mistakenly started working on Python implementation on the same branch. That is why I deleted that file. Do I still need to add that empty file?

Nevermind, I added the ```python/.gitkeep``` file again since it was in the ```master``` branch

2021-10-05 07:41 UTC, lohanidamodar requested changes
@GunjanDhanuka great work. Some changes.
Also there are two copies of every file in two different folders. Make sure to remove duplicates!

2021-10-05 07:41 UTC, lohanidamodar commented on dart/get-internet-speed/README.md
> +# 📧 getInternetSpeed
```suggestion
# 📧 Get Internet Speed
```

2021-10-05 07:41 UTC, lohanidamodar commented on dart/get-internet-speed/pubspec.yaml
> +dependencies:
```suggestion
```
As there are not dependencies we can remove this. Make sure it works after removing this.

2021-10-05 07:53 UTC, GunjanDhanuka commented on dart/get-internet-speed/README.md
> +# 📧 getInternetSpeed
Done!

2021-10-05 07:53 UTC, GunjanDhanuka commented on dart/get-internet-speed/pubspec.yaml
> +dependencies:
Done!

2021-10-06 14:16 UTC, GunjanDhanuka commented
> @GunjanDhanuka great work. Some changes. Also there are two copies of every file in two different folders. Make sure to remove duplicates!

@lohanidamodar I have made the requested changes! Can you please review them?

2021-10-10 13:20 UTC, lohanidamodar commented
@GunjanDhanuka please also add screenshot of successful execution and output.

2021-10-30 08:10 UTC, Meldiron requested changes
Please include a screenshot of successful execution and its output from Appwrite Console. Without that, we cannot proceed to merge the PR.

2021-11-17 08:08 UTC, christyjacob4 commented
@GunjanDhanuka Closing this PR since there hasn't been any activity in a while. Feel free to reopen it when you're ready to start working on it again.

2021-11-17 08:08 UTC, closed without merging