feat: implement ruby cloud function to send sms
appwrite/demos-for-functions pull request #115
Opened 2021-10-02 13:39 UTC by akashgp09

Resolves: #92

 Implemented ruby cloud function to send SMS to other user's phone number.

 - [x]  Write code for the function.
 - [x]  Test the function using Appwrite.
 - [x]  Write a README.md explaining what function does, how to use and customize it.

2021-10-04 08:00 UTC, Meldiron approved these changes
**Amazing** PR! 🤯  Approved by my, great job! Really clean PR, you just made my day.

2021-10-04 08:01 UTC, Meldiron commented
@lohanidamodar Please review code.

2021-10-04 08:07 UTC, Meldiron requested changes
One tiny comment after reviewing other PRs

2021-10-04 08:07 UTC, Meldiron commented on ruby/send-sms/main.rb
> +    puts message
What exactly is an output? Can we show example output in README.md?

2021-10-04 08:50 UTC, lohanidamodar requested changes
Looks great @akashgp09 just small changes!

2021-10-04 08:50 UTC, lohanidamodar commented on ruby/send-sms/README.md
> +## 🚀 Building and Packaging
```suggestion

## 🚀 Building and Packaging
```

2021-10-04 08:50 UTC, lohanidamodar commented on ruby/send-sms/README.md
> +$ bundle install
Need to update the GEM_HOME to `.appwrite` sub folder and packaged with the function when deployed.

2021-10-04 08:50 UTC, lohanidamodar commented on ruby/send-sms/README.md
> +├── main.rb
```suggestion
├── main.rb
├── .appwrite/
```

2021-10-05 07:31 UTC, lohanidamodar requested changes
@akashgp09 Great work. Just a small request.

2021-10-05 07:31 UTC, lohanidamodar commented on ruby/send-sms/main.rb
> +payload = JSON.parse(ENV['APPWRITE_FUNCTION_DATA'])
Hey can we handle some errors here, if data is not provided, not provided with all the correct fields, not with proper format? Thanks.

2021-11-17 08:17 UTC, merged

2021-11-17 08:17 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)