Feat implement translate text dart
appwrite/demos-for-functions pull request #117
Opened 2021-10-02 17:04 UTC by Rishabh-Negi

Related Issue #97

Created translateText folder in dart directory with main.dart, pubspec.yaml and README.md.

Please review the PR and suggest edits. Thanks!

2021-10-03 05:02 UTC, lohanidamodar requested changes

2021-10-03 05:02 UTC, lohanidamodar commented on dart/translate_text/README.md
> +$ cd demos-for-functions/dart/translate_text
You must add a step to set PUB_HOME variable, check other dart function demos.

2021-10-03 05:02 UTC, lohanidamodar commented on dart/translate_text/README.md
> +```
Folder structure must contain `.appwrite` folder with pub packages.

2021-10-03 05:02 UTC, lohanidamodar commented on dart/translate_text/main.dart
> +  final text = 'Hello world';
The text for translation should be received from the function execution payload.

2021-10-03 05:02 UTC, lohanidamodar commented on dart/translate_text/main.dart
> +
may be also a validation to make sure required env vars are supplied?

2021-10-03 07:02 UTC, Rishabh-Negi commented on dart/translate_text/main.dart
> +  final text = 'Hello world';
should the source language and destination language also be received from the function execution payload?
Thanks

2021-10-03 07:03 UTC, Rishabh-Negi commented on dart/translate_text/main.dart
> +
I added an If else block if some other type of validation is required please suggest.
Thanks

2021-10-04 06:42 UTC, lohanidamodar requested changes
@Rishabh-Negi awesome work 👍🏻 We need some more changes to make it even better.

2021-10-04 06:42 UTC, lohanidamodar commented on dart/translate_text/README.md
> +├── .appwrite
to make sure they know it's a directory not file
```suggestion
├── .appwrite/
```

2021-10-04 06:42 UTC, lohanidamodar commented on dart/translate_text/README.md
> +
As the function requires specific inputs in specific format, please include input/output section with proper details.

2021-10-10 13:20 UTC, lohanidamodar commented
@Rishabh-Negi please also add screenshot of successful execution and output in the description

2021-11-17 08:20 UTC, christyjacob4 commented
@Rishabh-Negi please add screenshots of successful executions. You can take a look at some of the merged PRs for reference.

2021-11-28 10:04 UTC, christyjacob4 commented
@Rishabh-Negi closing this PR for now since there has been no activity in quite a long time. Feel free to reopen it when you're ready to start working on it once again. 🙂

2021-11-28 10:04 UTC, closed without merging