feat: implement ruby cloud function to translate text
appwrite/demos-for-functions pull request #118
Opened 2021-10-03 01:34 UTC by akashgp09

Resolves: #97 

 Implemented ruby cloud function for translating text from one language to another using google translate.

 - [x]  Write code for the function.
 - [x]  Test the function using Appwrite.
 - [x]  Write a README.md explaining what function does, how to use and customize it.

2021-10-04 07:51 UTC, Meldiron requested changes
Great PR! 🤯 Left some comments during the review, please check them out.

2021-10-04 07:51 UTC, Meldiron commented on ruby/translate-text/main.rb
> +translation = GoogleTranslate.translate from: sourceLanguage, to: destinationLanguage, text: text
Can we include some way of authentification to GoogleTranslate? There might be some public API, but it surely is limited.  By authenticating, the limitation will be gone.

2021-10-04 07:51 UTC, Meldiron commented on ruby/translate-text/README.md
> +
Can we please also include example input and output?

2021-11-17 08:21 UTC, christyjacob4 approved these changes

2021-11-17 08:22 UTC, merged

2021-11-17 08:22 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)