chore: added object detection demo in python
appwrite/demos-for-functions pull request #12
Opened 2020-12-07 19:21 UTC by christyjacob4

Added a demo to leverage cloud functions and detect objects in an uploaded image

2020-12-07 21:05 UTC, eldadfux requested changes

2020-12-07 21:05 UTC, eldadfux commented on python/object-detection/README.md
> +```
Also need to add a listener for file events (storage.files.create, storage.files.update, storage.files.delete).

2020-12-07 21:05 UTC, eldadfux commented on python/object-detection/README.md
> +* **APPWRITE_KEY** - Create a key from the Appwrite console with the following scopes (`files.read` and `files.write`)
I think read scope should be enough

2020-12-07 21:05 UTC, eldadfux commented on python/object-detection/main.py
> +    print("Exception when calling RecognizeApi->recognize_detect_objects: %s\n" % e)
Code looks awesome, clean & elegant ❤️

2020-12-07 21:13 UTC, christyjacob4 commented on python/object-detection/README.md
> +```
Done

2020-12-07 21:13 UTC, christyjacob4 commented on python/object-detection/README.md
> +* **APPWRITE_KEY** - Create a key from the Appwrite console with the following scopes (`files.read` and `files.write`)
Done

2020-12-07 21:13 UTC, christyjacob4 commented on python/object-detection/main.py
> +    print("Exception when calling RecognizeApi->recognize_detect_objects: %s\n" % e)
Thanks ❤️  👍

2020-12-08 05:34 UTC, eldadfux approved these changes

2020-12-08 05:34 UTC, merged