Welcome Email using Cloud Functions
appwrite/demos-for-functions pull request #13
Opened 2020-12-09 14:48 UTC by christyjacob4

Cloud function demo in Nodejs leveraging the MailGun Email API to send welcome emails

2020-12-09 14:59 UTC, eldadfux requested changes
Minor comments, great work, much faster too!

2020-12-09 14:59 UTC, eldadfux commented on nodejs/welcome-email/README.md
> +Head over to your function in the Appwrite console and under the Settings Tab, enable the `users.create` event.
You need both user.create and account.create. They have the same payload, but triggered by different endpoints

2020-12-09 14:59 UTC, eldadfux commented on nodejs/welcome-email/index.js
> +	from: 'Welcome to Appwrite <welcome@appwrite.io>',
"Appwrite" might be confusing, what about "My Awesome New App"?

2020-12-09 15:20 UTC, christyjacob4 commented on nodejs/welcome-email/index.js
> +	from: 'Welcome to Appwrite <welcome@appwrite.io>',
Yea I agree. Will make those changes

2020-12-09 15:21 UTC, christyjacob4 commented on nodejs/welcome-email/README.md
> +Head over to your function in the Appwrite console and under the Settings Tab, enable the `users.create` event.
But when I was using the console to create a new user, I was able to trigger it with the `users.create` event 🤔

2020-12-09 20:56 UTC, eldadfux commented on nodejs/welcome-email/README.md
> +Head over to your function in the Appwrite console and under the Settings Tab, enable the `users.create` event.
yeh 100%, but for the function to be usable to end devs you would need to use both events.

2020-12-10 17:17 UTC, christyjacob4 commented on nodejs/welcome-email/README.md
> +Head over to your function in the Appwrite console and under the Settings Tab, enable the `users.create` event.
okay understood

2020-12-10 19:15 UTC, eldadfux approved these changes

2020-12-10 19:15 UTC, merged

2020-12-10 19:15 UTC, eldadfux commented
🔥