get-covid-stats JavaScript version
appwrite/demos-for-functions pull request #139
Opened 2021-10-05 19:46 UTC by mendoza

I implemented the get-covid-stats function for NodeJS, with README and package.json
mentioned on issue appwrite/appwrite#1923

# Executed function
![image](https://user-images.githubusercontent.com/30415552/136094587-78e654f4-f3cc-4719-9907-5313433cccfb.png)
# Execution log
![image](https://user-images.githubusercontent.com/30415552/136094630-762cd89d-1a38-4dc7-a3ce-4aaf253164c0.png)

2021-10-05 19:48 UTC, christyjacob4 requested changes
Also please share screenshots of a successful execution in the Appwrite Dashboard with the log message :+1:

2021-10-05 19:48 UTC, christyjacob4 commented on nodejs/get-covid-stats/package-lock.json
> +  "name": "cloud-functions-demo-nodejs",
You need to remove this file from the PR

2021-10-05 20:04 UTC, mendoza commented on nodejs/get-covid-stats/package-lock.json
> +  "name": "cloud-functions-demo-nodejs",
i removed the file i'm about to commit

2021-10-06 04:28 UTC, christyjacob4 requested changes

2021-10-06 04:28 UTC, christyjacob4 commented on nodejs/get-covid-stats/README.md
> +Can be triggered from manually from the Appwrite Console.
```suggestion
Can be triggered manually from the Appwrite Console.
```

2021-10-06 04:28 UTC, christyjacob4 commented on nodejs/get-covid-stats/README.md
> +
Let's use the same format for specifying the environment variables as the other examples. 
https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email#-environment-variables

2021-10-06 04:47 UTC, mendoza commented on nodejs/get-covid-stats/README.md
> +
will do

2021-10-06 04:57 UTC, christyjacob4 requested changes

2021-10-06 06:07 UTC, mendoza commented on nodejs/get-covid-stats/README.md
> +- APPWRITE_FUNCTION_DATA - Country code in ISO2 format, For example `US`, `HN` etc.
I made a longer but better paragraph on the environment variable section, to explain where we can set it too.

2021-10-30 08:30 UTC, Meldiron approved these changes
Looks good to me

2021-10-30 08:31 UTC, Meldiron commented
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

2021-10-30 08:31 UTC, merged