demo function for mailchimp subscribe
appwrite/demos-for-functions pull request #140
Opened 2021-10-05 20:52 UTC by benceHornyak

## Execution log (fraction of the screenshot)

![image](https://user-images.githubusercontent.com/12515595/136100618-b684f56b-76e4-437b-a6f4-ab05593192f5.png)

2021-10-06 04:36 UTC, christyjacob4 requested changes

2021-10-06 04:36 UTC, christyjacob4 commented on nodejs/subscribe-to-mailchimp/README.md
> +A sample nodejs Cloud Function for subscribing a mailchimp newsletter
```suggestion
A sample nodejs Cloud Function for subscribing to a Mailchimp newsletter
```

2021-10-06 04:36 UTC, christyjacob4 commented on nodejs/subscribe-to-mailchimp/README.md
> +Your data must include the following field:
Mention specifically that the `APPWRITE_FUNCTION_DATA` variable must contain this data

2021-10-06 04:36 UTC, christyjacob4 commented on nodejs/subscribe-to-mailchimp/README.md
> +* Click 'Activate'
Also add a ## Trigger section and mention how this function can be triggered like the other examples we already have in the repo.

2021-10-30 08:29 UTC, Meldiron approved these changes
Looks good to me

2021-10-30 08:29 UTC, Meldiron commented
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

2021-10-30 08:29 UTC, merged