Feat implement backup to storage node js
appwrite/demos-for-functions pull request #146
Opened 2021-10-06 15:45 UTC by henrhie

Could not generate an in-memory file to be sent to the storage API
The function generates the CSV file on disk and sends it to the storage API.

2021-10-30 08:38 UTC, Meldiron requested changes
Something is not right, it shows 217 files changed. I believe node_modules s included, can we please make sure to exclude this folder?

2021-11-28 10:41 UTC, christyjacob4 requested changes
Please address the comments 👍  Rest looks great ⭐

2021-11-28 10:41 UTC, christyjacob4 commented on nodejs/backup-to-storage/README.md
> +A sample NodeJS Cloud Function for creating a backup of every document in every collecion of your database in Cloud Storage.
```suggestion
A sample NodeJS Cloud Function for creating a backup of every document in every collection of your database in Cloud Storage.
```

2021-11-28 10:41 UTC, christyjacob4 commented on nodejs/backup-to-storage/README.md
> +- **APPWRITE_FUNCTION_PROJECT_ID** - Your Appwrite Project ID
```suggestion
```

You can remove this env var. This is passed to the runtime by default

2021-11-28 10:41 UTC, christyjacob4 commented on nodejs/backup-to-storage/README.md
> +$npm install
```suggestion
$ cd demos-for-functions/nodejs/backup-to-storage
$ npm install
```

2021-11-28 10:41 UTC, christyjacob4 commented on nodejs/backup-to-storage/README.md
> +- create a tarfile using the command below:
```suggestion
- Create a tarfile using the command below:
```

2021-11-28 10:41 UTC, christyjacob4 commented on nodejs/backup-to-storage/README.md
> +$ tar -zcvf code.tar.gz backup-to-storage
```suggestion
$ cd ..
$ tar -zcvf code.tar.gz backup-to-storage
```

2021-11-28 10:41 UTC, christyjacob4 commented on nodejs/backup-to-storage/README.md
> +- Navigate to the Overview Tab of your Cloud Function > Deploy Tab(scroll down a bit)
```suggestion
- Navigate to the Overview Tab of your Cloud Function > Deploy Tab (scroll down a bit)
```

2021-11-28 16:16 UTC, merged

2021-11-28 16:16 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)