docs: python template
appwrite/demos-for-functions pull request #15
Opened 2020-12-11 14:37 UTC by christyjacob4

Templates for python. 
@eldadfux please let me if this general structure is okay and I can do the same for the other languages.

2020-12-12 05:05 UTC, eldadfux commented
After adding all the templates, please add a section about them in the main readme, under "contributing". This would help encourage contributors to follow the same standard.

2020-12-12 06:58 UTC, christyjacob4 commented
Sure @eldadfux  👍 will do

2020-12-14 17:43 UTC, christyjacob4 commented on python/template/README.md
> +# Template
Shall I keep all the headings similar to the other example READMEs ?

2020-12-14 18:17 UTC, christyjacob4 commented on python/template/README.md
> +# Template
Done 👍

2020-12-14 18:17 UTC, christyjacob4 commented on python/template/README.md
> +* Clone the repo
Done 👍

2020-12-14 18:21 UTC, christyjacob4 commented on python/template/README.md
> +```
We can continue to use Triggers for the actual events that trigger the cloud function. 
Entrypoint can be mentioned in the `Building and Packaging` section since that seems a more relevant place for it to be. Let me know what you think

2020-12-14 18:56 UTC, eldadfux requested changes
Minor comments, latest updates looks good 👍

2020-12-14 18:56 UTC, eldadfux commented on deno/template/index.js
> +    .setEndpoint('http://localhost/v1')
Localhost can indicate that this might work and mislead devs. This should be a public domain or accessible IP address.

2020-12-14 18:56 UTC, eldadfux commented on php/template/index.php
> +    ->setEndpoint('http://localhost/v1') // Your API Endpoint
Localhost can indicate that this might work and mislead devs. This should be a public domain or accessible IP address.

2020-12-14 18:56 UTC, eldadfux commented on ruby/template/main.rb
> +    .set_endpoint('http://localhost/v1') # Your API Endpoint
Localhost can indicate that this might work and mislead devs. This should be a public domain or accessible IP address.

2020-12-14 19:01 UTC, eldadfux commented on python/template/README.md
> +```
Agree.

2020-12-14 19:09 UTC, christyjacob4 commented on deno/template/index.js
> +    .setEndpoint('http://localhost/v1')
Nice Catch 😃  
Fixed it

2020-12-16 14:31 UTC, merged