sendSMSMessageBird() php implementation
appwrite/demos-for-functions pull request #156
Opened 2021-10-07 08:36 UTC by ramdevcm

2021-10-20 15:48 UTC, ramdevcm commented
@lohanidamodar could you please review this PR

2021-10-30 08:47 UTC, Meldiron requested changes
Requested few changes.

2021-10-30 08:47 UTC, Meldiron commented on php/send-message-bird-sms/readme.md
> +</div>
Let's move screenshot of successful execution out of readme file and lets put it as comment on the PR.

2021-10-30 08:47 UTC, Meldiron commented on php/send-message-bird-sms/readme.md
> +Output log will be obtained
Let's explain how people can trigger the function here - either manually by pressing "execute now" on the function in appwrite console or using `createExecution` in any of our client/server-side SDK

2021-10-30 08:47 UTC, Meldiron commented on php/send-message-bird-sms/readme.md
> +</div>
We explained it well, let's remove this screenshot.

2021-10-30 08:47 UTC, Meldiron commented on php/send-message-bird-sms/readme.md
> +* **RECIPIENT** - Receiver phone number
Reciever will change in every request. Lets use `APPWRITE_FUNCTION_DATA` for that.

2021-11-28 10:46 UTC, christyjacob4 commented
@ramdevcm  closing this PR for now since there has been no activity in quite a long time. Feel free to reopen it when you're ready to start working on it once again. 🙂

2021-11-28 10:46 UTC, closed without merging