feat: generateWebsiteScreenshot
appwrite/demos-for-functions pull request #175
Opened 2021-10-08 11:31 UTC by krishguptadev

**A part of https://github.com/appwrite/appwrite/issues/1929**

- [x] Fork & clone Appwrite's demos-for-function repository
- [x] Create feat-implement-generate-website-screenshot-X branch where X is programming language you used (create branch name patch-1 for a little help with the code and don't know how to rename)
- [x] Write code for the function in folder X/generate-website-screenshot/ where X is programming language you used
- [x] Test the function using Appwrite
- [x] Write a README.md explaining what function does, how to use and customize it. Here is an example.
- [x] Submit pull request to our demos-for-function repository

## Successful Execution:

![image](https://user-images.githubusercontent.com/91655303/136683335-0ba82822-e7f9-40d7-a0fa-e3534d60cb32.png)

## Console Output

```sh
# $ID refers to the ID of the storedFile

Stored screenshot with id: $ID
```

![image](https://user-images.githubusercontent.com/91655303/136698943-67e33cc1-9b33-481b-abb6-bbd29956947e.png)

### Dashboard

![image](https://user-images.githubusercontent.com/91655303/137575797-01ccb3e6-60a8-4bd4-ba8a-aa48d958d870.png)

**RR: @Meldiron**

2021-10-10 13:35 UTC, lohanidamodar commented
@krishguptadev for successful execution can you also add the screenshot of function log screen.

2021-10-30 08:55 UTC, Meldiron requested changes
Requested few changes.

2021-10-30 08:55 UTC, Meldiron commented on deno/generate-website-screenshot/index.js
> +
Let's explain this format in the README file, so people know what to input

2021-10-30 08:55 UTC, Meldiron commented on deno/generate-website-screenshot/index.js
> +    console.log(`Stored screenshot with id: ${storedFile["$id"]}`);
Let's only return fileID, so the frontend can use it without parsing. Also, please let's document what user can expect as input in README file.

2021-10-30 08:55 UTC, Meldiron commented on deno/generate-website-screenshot/README.md
> +* Click 'Activate'
Let's include "Trigger" section where we explain the function can be executed either manually in appwrite console by clicking "execute now" on the function or by running `createExecution` using client/server-side SDKs.

2021-10-31 07:11 UTC, krishguptadev commented on deno/generate-website-screenshot/index.js
> +    console.log(`Stored screenshot with id: ${storedFile["$id"]}`);
Like?

```suggestion
    console.log(storedFile["$id"]);
```

2021-10-31 07:13 UTC, krishguptadev commented on deno/generate-website-screenshot/README.md
> +* Click 'Activate'
```suggestion
* Click 'Activate'

## 🎯 Trigger
You can trigger the function by clicking on "Execute now" in the Appwrite console or using `createExecution` function from one of our Client-side or Server-side SDKs. 
```

2021-11-28 11:11 UTC, christyjacob4 commented on deno/generate-website-screenshot/README.md
> +* **APPWRITE_PROJECT_ID** - Project ID of the Appwrite Project
```suggestion
```

You can exclude this here since `APPWRITE_FUNCTION_PROJECT_ID ` is automatically passed to the cloud function

2021-11-28 11:11 UTC, christyjacob4 commented on deno/generate-website-screenshot/README.md
> +* **APPWRITE_ENDPOINT** - Appwrite Endpoint to use
```suggestion
* **APPWRITE_ENDPOINT** - The endpoint of your Appwrite instance 
```

2021-11-28 11:16 UTC, christyjacob4 commented
@krishguptadev  Please attach screenshots of the logs from the execution as well as a preview of the saved image

2021-11-29 11:52 UTC, closed without merging