Implement merge function from cloud-converter api using appwrite pdf …
appwrite/demos-for-functions pull request #179
Opened 2021-10-08 19:49 UTC by geryjuhasz

…files

2021-10-30 08:50 UTC, Meldiron requested changes
Please include a screenshot of successful execution and its output from Appwrite Console. Without that, we cannot proceed to merge the PR.

Here is an example: https://github.com/appwrite/demos-for-functions/pull/165
(we only need second and third screenshot)

2021-10-30 10:29 UTC, geryjuhasz commented
<img width="1768" alt="logs" src="https://user-images.githubusercontent.com/4499900/139529284-c2a7af06-67f9-4844-9190-cb77c9e32231.png">
<img width="1768" alt="logs" src="https://user-images.githubusercontent.com/4499900/139529286-f9d49f05-1bbf-4ee3-85de-66ae9f3f30b4.png">

2021-10-30 11:39 UTC, geryjuhasz commented
@Meldiron pls check :)

2021-11-28 11:25 UTC, christyjacob4 commented on php/merge-cloud-convert-files/README.md
> +* **APPWRITE_FUNCTION_PROJECT_ID** - AppWrite Project ID
```suggestion
```
You can remove this since it's automatically passed to the cloud function

2021-11-28 11:27 UTC, christyjacob4 commented on php/merge-cloud-convert-files/README.md
> +
you are missing the tar file creation steps in between. You can use this readme as an example https://github.com/appwrite/demos-for-functions/blob/master/php/generate-website-screenshot/README.md

2021-11-28 11:30 UTC, christyjacob4 commented on php/merge-cloud-convert-files/index.php
> +
Please run this file through the [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to ensure consistent formatting

2021-11-28 11:30 UTC, christyjacob4 requested changes
Awesome work 👏 
Please remove the `composer.lock` file from the PR and address the remaining comments 🙂

2021-12-19 17:18 UTC, christyjacob4 commented
@geryjuhasz  closing this PR for now. Please feel free to reopen it when you're ready to start working on it once again.

2021-12-19 17:18 UTC, closed without merging