Made clarifications to README for Nodejs welcome-email.
appwrite/demos-for-functions pull request #18
Opened 2020-12-17 03:03 UTC by Shaka-n

Started work on https://github.com/appwrite/demos-for-functions/issues/16 but had trouble figuring out exactly what to do to get example working. Made changes to README to help other beginners onboard faster.

2020-12-17 11:54 UTC, christyjacob4 commented on .gitignore
> +nodejs/welcome-email/package-lock.json
This would become too specific to `welcome-email`. I would suggest the following 
```suggestion
nodejs/**/package-lock.json
nodejs/**/node_modules
```

Similarly for all the other languages (folder and filenames must be according to their respective package managers)

2020-12-17 12:02 UTC, christyjacob4 commented on nodejs/welcome-email/README.md
> +Use 'Node.js 14.5' environment.
Would be better to ignore the versions since they will keep changing.

2020-12-17 12:05 UTC, christyjacob4 commented on nodejs/welcome-email/README.md
> +## ☁️ Make a New Cloud Function
I don't think we need this section. We are trying to keep all the READMEs consistent, concise and have the same structure. You can refer to the other demos under `python`, `ruby` etc.
 
If this change is made, it would have to be reflected in all the other READMEs and IMHO it might become redundant for a basic step.

2020-12-17 12:06 UTC, christyjacob4 commented on nodejs/welcome-email/README.md
> +* Navigate to Overview Tab of your Cloud Function
```suggestion
* Navigate to Overview Tab of your Cloud Function > Deploy Tag
```

2020-12-17 12:08 UTC, christyjacob4 commented on nodejs/welcome-email/README.md
> +* Navigate to Overview Tab of your Cloud Function
```suggestion
* Navigate to the Overview Tab of your Cloud Function > Deploy Tag
```

2020-12-17 12:10 UTC, christyjacob4 commented on nodejs/welcome-email/index.js
> +const payload= {}
This cloud function is supposed to be triggered as a result of a `users.create` event.
So the email ID and name of the user would be passed as ENV variables to the Cloud Function by the Appwrite server. We don't need to hard code it here.

2020-12-17 12:10 UTC, christyjacob4 requested changes
Please refer to comments.

2020-12-17 12:11 UTC, christyjacob4 commented on nodejs/welcome-email/README.md
> +* Deploy Tag
```suggestion
```

2020-12-17 15:03 UTC, Shaka-n commented on .gitignore
> +nodejs/welcome-email/package-lock.json
Right, makes sense.

2020-12-17 15:09 UTC, Shaka-n commented on nodejs/welcome-email/README.md
> +## ☁️ Make a New Cloud Function
Yep, I can see now the pattern with the other READMEs.

2020-12-17 15:11 UTC, Shaka-n commented on nodejs/welcome-email/index.js
> +const payload= {}
Yes, this was my mistake. I only did this as part of testing things out and intended to remove it before committing.

2020-12-18 10:28 UTC, christyjacob4 commented on .gitignore
> +nodejs/welcome-email/node_modules
You wouldn't need this line now

2020-12-18 10:29 UTC, christyjacob4 requested changes
Looks good. Just one last bit 🎉

2020-12-18 16:39 UTC, Shaka-n commented on .gitignore
> +nodejs/welcome-email/node_modules
Right!

2020-12-19 07:06 UTC, christyjacob4 approved these changes

2020-12-30 12:46 UTC, merged

2020-12-30 12:47 UTC, eldadfux commented
Thanks @Shaka-n ! 🚀