feat: deno file backup
appwrite/demos-for-functions pull request #188
Opened 2021-10-09 07:43 UTC by krishguptadev

**A part of https://github.com/appwrite/appwrite/issues/2028**

- [x] Fork & clone Appwrite's demos-for-function repository
- [x] Create feat-implement-file-backup-X branch where X is programming language you used (create branch name patch-2 by mistake and don't know how to rename)
- [x] Write code for the function in folder X/file-backup/ where X is programming language you used
- [x] Test the function using Appwrite
- [x] Write a README.md explaining what function does, how to use and customize it. Here is an example.
- [x] Submit pull request to our demos-for-function repository

## Successful Execution:

![image](https://user-images.githubusercontent.com/91655303/136656312-2aaeb942-9c8b-425b-b522-7ef2129878fe.png)

## Console Output

```sh
backup created!
```

### Dashboard

![image](https://user-images.githubusercontent.com/91655303/137576085-675746e9-ae56-4bd1-9167-d2f70185cfe1.png)

**RR: @christyjacob4**

2021-10-30 09:12 UTC, Meldiron commented on deno/file-backup/index.js
> +  let retrievedCollections = await database.listCollections();
You need to write a loop that uses `sum` from the response to calculate how many pages are there. Then, you can use `limit` and `offset` to get everything.. Let's take a look at this example:

I listDocuments with `limit` 100 and `offset 0`.. I get an array with 100 documents and `sum` of 923.
That means, there are 823 more documents I need to get - so I need to run my function 9 more times. 8 times I would get 100 more documents and the last one would only give 23 more. So I fire these requests in for loop by increasing the offset:
1. limt=100 offset=100
2. limt=100 offset=200
3. limt=100 offset=300
4. limt=100 offset=400
5. limt=100 offset=500
6. limt=100 offset=600
7. limt=100 offset=700
8. limt=100 offset=800
9. limt=100 offset=900

If I merge all documents from all of these requests, I should have 923 documents in total from 10 requests. This is how you can implement pagination.

2021-11-28 03:44 UTC, krishguptadev commented on deno/file-backup/index.js
> +  let retrievedCollections = await database.listCollections();
@Meldiron like this?

```suggestion
  let retrievedCollections = await database.listCollections({ limit: 100 });
```

2021-11-28 11:43 UTC, christyjacob4 commented on deno/file-backup/README.md
> +* **APPWRITE_PROJECT_ID** - Project ID of the Appwrite Project
```suggestion
```
APPWRITE_FUNCTION_PROJECT_ID is already passed to the function by Appwrite.

2021-11-28 11:47 UTC, christyjacob4 commented on deno/file-backup/index.js
> +  let retrievedCollections = await database.listCollections();
@krishguptadev  you need to use the `limit` and `offset` parameters of the [listCollections](https://appwrite.io/docs/server/database#databaseListCollections)  endpoint to paginate through all the collections in this project .

2021-11-28 11:48 UTC, christyjacob4 commented on deno/file-backup/index.js
> +    let retrievedDocuments = await database.listDocuments(collection.$id);
Likewise, @krishguptadev  you need to make sure you create a backup of all the documents in the database. This will only return the first 25 documents

2021-11-28 11:48 UTC, christyjacob4 requested changes
Please address the comments

2021-11-29 11:00 UTC, closed without merging