Implementing subscribe to sendgrid PHP example function
appwrite/demos-for-functions pull request #224
Opened 2021-10-14 17:07 UTC by Shylajhaa

Implementing subscribe to sendgrid PHP example function [#1915](https://github.com/appwrite/appwrite/issues/1915)

1. Created a function in project
<img width="725" alt="Screenshot 2021-10-18 at 8 48 35 PM" src="https://user-images.githubusercontent.com/22257998/137760617-7614a789-02be-4133-a9b3-f60396caed77.png">

2. Execute function with email as input
<img width="795" alt="Screenshot 2021-10-18 at 8 47 57 PM" src="https://user-images.githubusercontent.com/22257998/137760739-6c45d062-bbd5-4f9a-99fd-8daed78e3e7a.png">

3. On successful execution message is printed to console
<img width="1033" alt="Screenshot 2021-10-18 at 8 48 18 PM" src="https://user-images.githubusercontent.com/22257998/137760908-390f5283-a31f-4691-80e9-822918db2d5c.png">

2021-10-17 18:54 UTC, christyjacob4 commented
Please attach screenshots of a successful execution along with the console output

2021-11-28 13:11 UTC, christyjacob4 commented on php/subscribe-to-sendgrid/README.md
> +- Click 'Activate'
You can add the **Trigger** section back and mention that this function is triggered manually. Like this example here https://github.com/appwrite/demos-for-functions/pull/154/files#diff-8686b4afc9e25133e17a513bc8d56a4d49a0a2cfa8e23dd6436438d33fe1d618R47

2021-11-28 13:11 UTC, christyjacob4 requested changes
please address one last comment and we can merge this 😄 

Awesome work !

2021-11-28 14:00 UTC, Shylajhaa commented
> please address one last comment and we can merge this 😄
> 
> Awesome work !

@christyjacob4 Done, we can merge now. Thanks :)

2021-11-28 14:12 UTC, christyjacob4 commented
Awesome work @Shylajhaa  👏

2021-11-28 14:13 UTC, merged

2021-11-28 14:13 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)