Feat implement send message bird whatsapp msg node
appwrite/demos-for-functions pull request #231
Opened 2021-10-15 16:14 UTC by codingsamurai-10

Sending a custom Whatsapp Message to a given phone number using Messagebird API.
appwrite/appwrite#1891

# Input
![1-input](https://user-images.githubusercontent.com/58487637/139007605-a6b84f19-5164-408b-9cb4-b94066f09fd8.png)

# Successful execution
![2-success-execution](https://user-images.githubusercontent.com/58487637/139007632-226a50e5-99d4-4519-b0ce-22d612c13837.png)

# STDOUT
![3-stdout](https://user-images.githubusercontent.com/58487637/139007653-4288e646-b9a4-46f8-97c5-d23541aec4b7.png)

# Whatsapp message received
![4-wapp](https://user-images.githubusercontent.com/58487637/139007678-660d23b9-1775-49f4-9c24-dbc790ceec49.png)

2021-10-30 09:14 UTC, Meldiron requested changes
Let's remove unnecessary connection to Appwrite (not used) and also mark the error as.. well, error. (using console.error)

2021-10-30 09:14 UTC, Meldiron commented on nodejs/send-message-bird-whatsapp-msg/index.js
> +    return console.log(err);
```suggestion
    return console.error(err);
```

2021-10-30 09:14 UTC, Meldiron commented on nodejs/send-message-bird-whatsapp-msg/index.js
> +
```suggestion

```

2021-10-30 09:14 UTC, Meldiron commented on nodejs/send-message-bird-whatsapp-msg/README.md
> +- **APPWRITE_API_KEY** - Appwrite project's API key
```suggestion
```

2021-10-30 09:14 UTC, Meldiron approved these changes
Looks good to me

2021-10-30 09:14 UTC, Meldiron commented
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

2021-10-30 09:15 UTC, merged

2021-11-06 13:02 UTC, codingsamurai-10 commented
Thank you for making the changes @Meldiron <3