Implement createCloudConvertArchive function
appwrite/demos-for-functions pull request #244
Opened 2021-10-19 06:39 UTC by geryjuhasz

2021-10-30 10:23 UTC, geryjuhasz commented
<img width="1762" alt="output" src="https://user-images.githubusercontent.com/4499900/139529152-a2f26930-43b5-40fa-b589-bdf5af528b67.png"
<img width="1545" alt="logs" src="https://user-images.githubusercontent.com/4499900/139529154-4b081714-0494-41bc-9ca4-fd57b53dea78.png">
>

2021-11-28 14:04 UTC, christyjacob4 commented on php/create-cloud-convert-archive/README.md
> +A sample PHP Cloud Function for archiving files from AppWrite storage.
```suggestion
A sample PHP Cloud Function for archiving files from Appwrite storage.
```

2021-11-28 14:04 UTC, christyjacob4 commented on php/create-cloud-convert-archive/README.md
> +# 📧 Archive files using CloudConverter's `createCloudConvertArchive` function
```suggestion
# 📧 Archive files using CloudConvert's `createCloudConvertArchive` function
```

2021-11-28 14:05 UTC, christyjacob4 commented on php/create-cloud-convert-archive/README.md
> +* **APPWRITE_FUNCTION_PROJECT_ID** - AppWrite Project ID
```suggestion
```
You can remove this . the project ID is automatically passed to the function

2021-11-28 14:05 UTC, christyjacob4 commented on php/create-cloud-convert-archive/README.md
> +* **APPWRITE_ENDPOINT** - AppWrite Domain
```suggestion
* **APPWRITE_ENDPOINT** - Appwrite Domain 
```

2021-11-28 14:05 UTC, christyjacob4 commented on php/create-cloud-convert-archive/README.md
> +* **APPWRITE_API_KEY** - AppWrite API key
```suggestion
* **APPWRITE_API_KEY** - Appwrite API key
```

2021-11-28 14:06 UTC, christyjacob4 commented on php/create-cloud-convert-archive/README.md
> +```
you're missing the instructions to package this function as a tar file. Please include those steps. You can use this as a reference https://github.com/appwrite/demos-for-functions/tree/master/php/get-covid-stats

2021-11-28 14:08 UTC, christyjacob4 commented on php/create-cloud-convert-archive/README.md
> +php index.php fileId1 fileId2 ...
This does not seem right.  You need to provide the triggers for this function like this https://github.com/appwrite/demos-for-functions/tree/master/php/get-covid-stats#-trigger

Here, you can also mention that you need to pass the files as part of the function data when triggering it 
```
path1 path2 path3  
```

2021-11-28 14:09 UTC, christyjacob4 requested changes
Please address the comments and remove the `composer.lock` file

2021-12-19 17:29 UTC, christyjacob4 commented
@geryjuhasz closing this issue for now. Please feel free to reopen it/ create a new one when you're ready to start working on it once again

2021-12-19 17:29 UTC, closed without merging