Simple Firebase Push Notification
appwrite/demos-for-functions pull request #258
Opened 2021-10-22 17:57 UTC by s3ppo

2021-11-06 13:15 UTC, s3ppo commented
done

2021-11-08 11:31 UTC, Meldiron requested changes
Before I review, please check "files changed" tab. There are 2 folders with source code - `push-nitification` and `PushNotification`. Which one is correct? Can we please remove one of them?

2021-11-08 11:56 UTC, s3ppo commented
sry my bad, i forgot to remove the old folder :(
please try again

2021-11-28 14:20 UTC, christyjacob4 commented on nodejs/push-notification/README.md
> +* Click 'Activate'
Please add a triggers section like the other examples. You can use this as a reference https://github.com/appwrite/demos-for-functions/tree/master/nodejs/object-detection#-trigger

2021-11-28 14:21 UTC, christyjacob4 commented on nodejs/push-notification/index.js
> +var serviceAccount = require("/usr/local/src/serviceAccountKey.json");
Any reason you used the absolute path ? 
Isn't it better to use relative path like `./serviceAccountKey.json` ? 🤔

2021-11-28 14:22 UTC, christyjacob4 commented on nodejs/push-notification/index.js
> +    .setEndpoint(process.env.APPWRITE_ENDPOINT)
The endpoint needs to be included as an environment variable and needs to be mentioned in the environment variables section of  your README.

2021-11-28 14:22 UTC, christyjacob4 commented on nodejs/push-notification/index.js
> +    .setKey(process.env.APPWRITE_API_KEY);
The Key needs to be included as an environment variable and needs to be mentioned in the environment variables section of  your README.

2021-11-28 14:23 UTC, christyjacob4 commented on nodejs/push-notification/index.js
> +    databaseURL: "<place_your_firebase_url_here>"
The Firebase URL needs to be included as an environment variable and needs to be mentioned in the environment variables section of  your README.

2021-11-28 14:24 UTC, christyjacob4 requested changes
Please address the comments

2021-11-28 14:24 UTC, christyjacob4 commented on nodejs/push-notification/index.js
> +const token = "<place_user_token_here>";
Which token is this ? This needs to be passed as an env variable or as part of the `FUNCTION_DATA` whichever is most appropriate

2021-12-19 18:04 UTC, christyjacob4 commented
@s3ppo  closing this PR for now. Please feel free to reopen it/ create a new one when you are ready to work on it once again

2021-12-19 18:04 UTC, closed without merging