mergeCloudConvertFiles(): Add Kotlin implementation
appwrite/demos-for-functions pull request #264
Opened 2021-10-26 05:33 UTC by daniel-shuy

Partially implements appwrite/appwrite#1931

# Input
![image](https://user-images.githubusercontent.com/17351764/138812933-9204982d-8e76-4e06-91bd-d2be8d84908c.png)

# Successful Execution
![image](https://user-images.githubusercontent.com/17351764/139103832-dbc9a9aa-2e50-4178-9309-00212de68b08.png)

# CloudConvert Console
![image](https://user-images.githubusercontent.com/17351764/138813496-5223608a-7be4-48ea-a58d-c822f1a11b94.png)

# Output
![image](https://user-images.githubusercontent.com/17351764/138812996-b72988c0-c275-4f9d-9937-bada19181952.png)
- The Function Data is printed to the console
- The metadata of the merged PDF file is printed to the console

![image](https://user-images.githubusercontent.com/17351764/138865957-0ee2a1aa-62f5-48fc-8897-f725a79d39c0.png)

A few ways this improves over other Kotlin examples:
- Uses the [Gradle Shadow Plugin](https://imperceptiblethoughts.com/shadow/) to generate a uber/fat-JAR, and to minimize the JAR size (without it, just including the Kotlin standard library, [Appwrite SDK for Kotlin](https://github.com/appwrite/sdk-for-kotlin) and [CloudConvert Java SDK](https://github.com/cloudconvert/cloudconvert-java) would already exceed the 10MB size limit)
- Uses the [Gradle Application Plugin](https://docs.gradle.org/current/userguide/application_plugin.html) to build and create a TAR file in a single step (using `gradle shadowDistTar`), removing the need to manually TAR the JAR file
- Properly logs response messages on error from Appwrite/CloudConvert
- Uses coroutines to parallelize API calls. When not possible (eg. CloudConvert's client blocks the thread), falls back to Java parallel streams

2021-10-26 13:25 UTC, PineappleIOnic requested changes
Could you please not modify the README.md, We will do it ourselves later down the line :+1:

2021-11-28 14:52 UTC, christyjacob4 requested changes

2021-11-28 14:52 UTC, christyjacob4 commented on kotlin/merge-cloud-convert-files/gradlew
> +#!/usr/bin/env sh
you can exclude this file 🙂

2021-11-28 14:52 UTC, christyjacob4 commented on kotlin/merge-cloud-convert-files/gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
You can exclude this file

2021-11-28 14:52 UTC, christyjacob4 commented on kotlin/merge-cloud-convert-files/gradlew.bat
> +@rem
You can exclude this file

2021-11-28 14:52 UTC, christyjacob4 commented on kotlin/merge-cloud-convert-files/README.md
> +- **APPWRITE_API_KEY** - Mandatory. Your Appwrite API key with `files.read` and `files.write` permissions
At the moment it is not possible. 

It could be a possibility, but the problem is, a project can have multiple API keys. So which ones do we share with a cloud function ? So I dont think this should be something that's automatically available to the cloud function

2021-12-19 18:06 UTC, merged

2021-12-19 18:06 UTC, christyjacob4 commented
THANK YOU! All changes merged :partying_face:

Please reach out to me on discord to claim your Hacktoberfest swag! 

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.