sendMessageBirdWhatsappMsg(): Add Kotlin implementation
appwrite/demos-for-functions pull request #272
Opened 2021-10-26 18:17 UTC by daniel-shuy

Partially implements appwrite/appwrite#1891

Tested using [MessageBird WhatsApp Sandbox](https://dashboard.messagebird.com/en/whatsapp/sandbox) (see https://support.messagebird.com/hc/en-us/articles/360002109957-Start-testing-with-the-MessageBird-WhatsApp-Sandbox)

# Input
![image](https://user-images.githubusercontent.com/17351764/138936654-6d39bb03-acc6-4cb1-8dec-d5d4c04fda2f.png)

# Successful Execution
![image](https://user-images.githubusercontent.com/17351764/139104983-63a54466-a78f-4b01-8649-a592b49ca5c9.png)

# Output
![image](https://user-images.githubusercontent.com/17351764/138937323-4aa823be-abb3-4a1e-8c93-6b5b5ac5161b.png)
- The Function Data is printed to the console
- The MessageBird response is printed to the console

![image](https://user-images.githubusercontent.com/17351764/138937223-5651a398-bdee-4905-97ce-afc8e98d8cb0.png)

A few ways this improves over other Kotlin examples:
- Uses the [Gradle Shadow Plugin](https://imperceptiblethoughts.com/shadow/) to generate a uber/fat-JAR, and to minimize the JAR size (without it, just including the Kotlin standard library, [Appwrite SDK for Kotlin](https://github.com/appwrite/sdk-for-kotlin) and [CloudConvert Java SDK](https://github.com/cloudconvert/cloudconvert-java) would already exceed the 10MB size limit)
- Uses the [Gradle Application Plugin](https://docs.gradle.org/current/userguide/application_plugin.html) to build and create a TAR file in a single step (using `gradle shadowDistTar`), removing the need to manually TAR the JAR file
- Validates enum values and displays possible options in error message

2021-10-27 08:10 UTC, Meldiron approved these changes
Looks good to me

2021-11-17 12:04 UTC, christyjacob4 requested changes
You can remove the `gradle-wrapper` files to stay consistent with the other demos

Please use this as a reference https://github.com/appwrite/demos-for-functions/tree/master/kotlin/get-covid-stats

2021-11-17 12:04 UTC, christyjacob4 commented on kotlin/send-message-bird-whatsapp-msg/gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
You can remove this file

2021-11-17 12:04 UTC, christyjacob4 commented on kotlin/send-message-bird-whatsapp-msg/gradlew
> +# Copyright 2015 the original author or authors.
You can remove this file

2021-11-17 12:04 UTC, christyjacob4 commented on kotlin/send-message-bird-whatsapp-msg/gradlew.bat
> +@rem
You can remove this file

2021-11-17 16:34 UTC, daniel-shuy commented
@christyjacob4 done. Seems like an odd decision though since including the Gradle Wrapper seems like a standard practice for most Gradle projects

2021-11-28 14:45 UTC, christyjacob4 commented
@daniel-shuy I agree, gradle-wrapper would be handy if we were running this locally. 

But since we are creating a jar file out of this, a gradle-wrapper would be irrelevant. 🙂

2021-11-28 14:46 UTC, christyjacob4 approved these changes

2021-11-28 14:46 UTC, merged

2021-11-28 14:46 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)