Feat implement storage cleaner in java
appwrite/demos-for-functions pull request #284
Opened 2021-10-28 09:23 UTC by Prakhar-Agarwal-byte

Added a storage cleaner function demo in Java

Makes progress towards appwrite/appwrite#2031

2021-10-30 17:55 UTC, Prakhar-Agarwal-byte commented
@PineappleIOnic Please merge the PR now 😀

2021-10-31 13:46 UTC, Prakhar-Agarwal-byte commented
@PineappleIOnic Please merge the PR as today is the last day for claiming appwrite swags😅

2021-11-08 11:25 UTC, Meldiron requested changes

2021-11-08 11:25 UTC, Meldiron commented on java/storage-cleaner/src/main/java/StorageCleaner.java
> +                    new Continuation<Object>() {
Lets add pagination, this will only return 25 files.

2021-11-08 14:54 UTC, Prakhar-Agarwal-byte commented on java/storage-cleaner/src/main/java/StorageCleaner.java
> +                    new Continuation<Object>() {
In the API docs it's mentioned that it lists all user files. https://appwrite.io/docs/client/storage#storageListFiles

2021-11-28 15:45 UTC, christyjacob4 commented on java/storage-cleaner/src/main/java/StorageCleaner.java
> +                    new Continuation<Object>() {
@Prakhar-Agarwal-byte yes that endpoint can be used to list all the files. But you need to use the `limit` and `offset`parameters to get all of them.

2021-11-28 15:45 UTC, christyjacob4 requested changes
Please add support for pagination in your cloud function

2021-12-19 18:44 UTC, christyjacob4 commented
@Prakhar-Agarwal-byte closing this PR for now. Feel free to reopen it / create a new one when you're ready to start working on it once again

2021-12-19 18:44 UTC, closed without merging