Implementing backup to S3 Kotlin example function
appwrite/demos-for-functions pull request #285
Opened 2021-10-28 15:40 UTC by Shylajhaa

Implementing backup to S3 Kotlin example function

1. Created a function in project
<img width="713" alt="Screenshot 2021-10-28 at 8 23 44 PM" src="https://user-images.githubusercontent.com/22257998/139289067-8a604e9c-9d73-4375-93e0-22723733b1e6.png">

2. Execute function

3. On successful execution message is printed to console
<img width="1093" alt="Screenshot 2021-10-28 at 8 23 52 PM" src="https://user-images.githubusercontent.com/22257998/139289388-bc5f465e-4e9e-4db8-90f7-0ba304e75757.png">

4. File is uploaded to S3 Bucket
<img width="972" alt="Screenshot 2021-10-30 at 2 59 57 PM" src="https://user-images.githubusercontent.com/22257998/139527717-77c13225-d190-495f-8550-4d51afa4ec2a.png">

2021-10-30 10:01 UTC, Shylajhaa commented
@PineappleIOnic Made the necessary changes. Please check now

2021-10-31 09:10 UTC, Meldiron requested changes
Requested a few changes.

2021-10-31 09:10 UTC, Meldiron commented on kotlin/backup-to-s3/src/main/kotlin/BackupToS3.kt
> +                    database.listCollections().body?.string()
Please add pagination as this would only fetch the first 25 collections

2021-10-31 09:10 UTC, Meldiron commented on kotlin/backup-to-s3/src/main/kotlin/BackupToS3.kt
> +                    collectionsCsv!!.append("\n")
We are storing information (metadata) about the collection, but we are not storing data themselves. For that, we need to use "listDocuments". Also, let's make sure to implement pagination, otherwise, it would only backup 25 documents.

2021-11-28 15:50 UTC, christyjacob4 commented on kotlin/backup-to-s3/src/main/kotlin/BackupToS3.kt
> +            println(e)
`println` prints to `stdout`. Please print errors to `stderr` so Appwrite knows how to categorise the logs appropriately.

2021-11-28 15:51 UTC, christyjacob4 commented on kotlin/backup-to-s3/README.md
> +-- **APPWRITE_FUNCTION_PROJECT_ID** - Appwrite Project Id
```suggestion
```

This is automatically passed to the function from Appwrite. We don't need to include it as an env variable

2021-11-28 15:53 UTC, christyjacob4 commented on kotlin/backup-to-s3/src/main/kotlin/BackupToS3.kt
> +            System.getenv("AWS_API_SECRET"))).apply {
These variables are not declared in the env variables section of the readme. Please add all the environment variables that your function needs in the README.

2021-11-28 15:53 UTC, christyjacob4 commented on kotlin/backup-to-s3/src/main/kotlin/BackupToS3.kt
> +        val s3response = s3.putObject(PutObjectRequest(System.getenv("BUCKET_NAME"), "collections", file))
You need to include this env variable in the README and mention what it's used for.

2021-11-28 15:54 UTC, christyjacob4 requested changes
Please address the comments

2021-11-28 19:27 UTC, Shylajhaa commented
> Please address the comments
Addressed all comments @christyjacob4

2021-12-19 19:09 UTC, merged

2021-12-19 19:09 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on discord to claim your Hacktoberfest swag.

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership visibility settings, so your new Appwrite membership badge will show up on your personal GitHub profile.