Implementing backup to S3 Java example function
appwrite/demos-for-functions pull request #286
Opened 2021-10-28 17:10 UTC by Shylajhaa

Implementing backup to S3 Java example function

1. Created a function in project
<img width="718" alt="Screenshot 2021-10-28 at 10 28 33 PM" src="https://user-images.githubusercontent.com/22257998/139302735-3a5dc88f-d6eb-44e0-89f0-22727e2ed8e4.png">

2. Execute function

3. On successful execution message is printed to console
<img width="926" alt="Screenshot 2021-10-28 at 10 28 49 PM" src="https://user-images.githubusercontent.com/22257998/139302810-4f0db36d-4524-4017-bd74-cbc2a94650bc.png">

4. File is uploaded to S3
<img width="999" alt="Screenshot 2021-10-30 at 3 25 49 PM" src="https://user-images.githubusercontent.com/22257998/139528420-b2afd46b-7b65-455d-8a41-707281631d26.png">

2021-10-30 10:01 UTC, Shylajhaa commented
@PineappleIOnic Made the necessary changes. Please check now

2021-10-31 09:05 UTC, Meldiron commented
Connecting this PR to issue https://github.com/appwrite/appwrite/issues/1890

2021-10-31 09:09 UTC, Meldiron requested changes
Requested few changes.

2021-10-31 09:09 UTC, Meldiron commented on java/backup-to-s3/src/main/java/BackupToS3.java
> +                            .asJson();
Please let's use Appwrite library so we don't have to struggle with building the HTTP request. Also, please add pagination as this would only fetch first 25 collections

2021-10-31 09:09 UTC, Meldiron commented on java/backup-to-s3/src/main/java/BackupToS3.java
> +                collectionsCsv.append("\n");
We are storing information (metadata) about the collection, but we are not storing data themselves. For that, we need to use "listDocuments". Also, let's make sure to implement pagination, otherwise, it would only backup 25 documents.

2021-11-28 15:55 UTC, christyjacob4 requested changes
I have similar comments to that in your Kotlin PR. Please fix those 👍

2021-11-30 16:53 UTC, Shylajhaa commented on java/backup-to-s3/src/main/java/BackupToS3.java
> +                            .asJson();
@Meldiron I have worked on pagination. However while using AppwriteClient I'm facing issues discussed in this thread - https://discord.com/channels/564160730845151244/564161373148414012/914957241436749844

Can I just go ahead with using Unirest?

2021-11-30 16:57 UTC, Shylajhaa commented on java/backup-to-s3/src/main/java/BackupToS3.java
> +                            .asJson();
cc: @christyjacob4

2021-11-30 18:10 UTC, Shylajhaa commented
> I have similar comments to that in your Kotlin PR. Please fix those 👍

@christyjacob4 Addressed PR comments except moving to Appwrite Client, Have hit APIs using Unirest

2021-12-19 19:11 UTC, christyjacob4 approved these changes

2021-12-19 19:11 UTC, merged

2021-12-19 19:11 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on discord to claim your Hacktoberfest swag.

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership visibility settings, so your new Appwrite membership badge will show up on your personal GitHub profile.