Demo to create user profile document upon a new user account creation…
appwrite/demos-for-functions pull request #289
Opened 2021-10-29 03:36 UTC by gireeshp

… - issue#288

2021-11-01 09:19 UTC, Meldiron requested changes
Requested a few changes

2021-11-01 09:19 UTC, Meldiron commented on python/create_user_profile/main.py
> +user_collection_id = "617497ffb09f7"
Let's store this in environment variable as it changes for everyone.

2021-11-01 09:19 UTC, Meldiron commented on python/create_user_profile/README.md
> +```
Let's use readme file from some of the existing functions and let's stick to it's structure.

2021-11-02 01:52 UTC, gireeshp commented on python/create_user_profile/main.py
> +user_collection_id = "617497ffb09f7"
Done

2021-11-02 01:52 UTC, gireeshp commented on python/create_user_profile/README.md
> +```
Done

2021-11-02 01:53 UTC, gireeshp commented
Hi @Meldiron - suggested changes are implemented. Please take a look.

2021-11-08 11:23 UTC, Meldiron requested changes

2021-11-08 11:23 UTC, Meldiron commented on python/create_user_profile/main.py
> +    database.create_document(user_collection_id, {'user_id': userId, 'user_name': userName, 'email': email}, read=['*'], write=['*'])
Let's give write permissions only to the user, otherwise hackers would remove them all 😅

2021-11-08 22:08 UTC, gireeshp commented on python/create_user_profile/main.py
> +    database.create_document(user_collection_id, {'user_id': userId, 'user_name': userName, 'email': email}, read=['*'], write=['*'])
Hi @Meldiron  - removed the wildcard write permission.

2021-11-14 03:35 UTC, gireeshp commented
Hello @Meldiron  - can you check this pls?

2021-11-15 09:07 UTC, Meldiron approved these changes
Looks good to me

2021-11-15 09:07 UTC, merged