Feat implement convert cloud convert file php
appwrite/demos-for-functions pull request #297
Opened 2021-10-30 12:56 UTC by verenaroe

Part of [appwrite/appwrite#1933](https://github.com/appwrite/appwrite/issues/1933)

#### Initial Storage
<img width="1405" alt="grafik" src="https://user-images.githubusercontent.com/49275087/139533575-ff7b8a84-cd9b-4741-8acb-bc9182ec45eb.png">

#### Execution input
<img width="1146" alt="grafik" src="https://user-images.githubusercontent.com/49275087/139533604-12929e1a-61d5-47fa-aae3-4ed1c9518665.png">

#### Execution log
<img width="1372" alt="grafik" src="https://user-images.githubusercontent.com/49275087/139533626-cab18b6f-8f77-4805-914c-596dd3e369d9.png">

#### Execution output
<img width="930" alt="grafik" src="https://user-images.githubusercontent.com/49275087/139533633-6230eed3-f36f-4283-b5da-188639cc87a5.png">

#### Final storage
<img width="1345" alt="grafik" src="https://user-images.githubusercontent.com/49275087/139533650-9dd1eb32-b2d1-4ce3-beab-1f1f468b0975.png">

2021-11-28 16:54 UTC, christyjacob4 commented on php/convert-cloud-convert-file/README.md
> +$ tar -zcvf code.tar.gz .
```suggestion
$ cd ..
$ tar -zcvf code.tar.gz  convert-cloud-convert-file
```

2021-11-28 16:54 UTC, christyjacob4 commented on php/convert-cloud-convert-file/README.md
> +## 🎯 Schedule
```suggestion
## 🎯 Trigger
```

2021-11-28 16:55 UTC, christyjacob4 commented on php/convert-cloud-convert-file/README.md
> +## 🎯 Schedule
Mention in the description that this function uses a CRON schedule as a trigger.

2021-11-28 16:55 UTC, christyjacob4 requested changes
Please address the comments

2021-11-29 07:50 UTC, verenaroe commented
I addressed all your comments

2021-12-19 18:08 UTC, merged

2021-12-19 18:08 UTC, christyjacob4 commented
THANK YOU! All changes merged :partying_face:

Please reach out to me on discord to claim your Hacktoberfest swag! 

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.