Working version of welcome email for Deno.
appwrite/demos-for-functions pull request #30
Opened 2021-01-03 18:36 UTC by Shaka-n

I used a simplified client to interact with the Mailgun API because I had trouble getting Deno's compatibility module to import the mailgun.js module. I was also not sure how to manually alter the event payload to test if the function fully works in AppWrite, but I have it working locally. Looking forward to making any necessary changes :)

2021-01-03 20:27 UTC, TorstenDittmann commented on deno/welcome-email/index.js
> +import MailgunClient from "https://gist.githubusercontent.com/webdeb/837886746bf43e46effb269c68f0f5ce/raw/1eff4888e78ea1d8d2998c62284d1f7711ce205c/Mailgun.ts"
Instead of importing `https://gist.githubusercontent.com/webdeb/837886746bf43e46effb269c68f0f5ce/raw/1eff4888e78ea1d8d2998c62284d1f7711ce205c/Mailgun.ts`, you could put this file in the directory. This way we can make sure it is always available 🙂

2021-01-11 15:54 UTC, Shaka-n commented
Thanks Torsten! I could put that file in the directory, but I'm not sure what the fair use is around that. I figured it would be easier if I removed that external import and replaced it with a simple fetch request. Let me know if you disagree though!

2021-01-11 16:01 UTC, TorstenDittmann commented
> Thanks Torsten! I could put that file in the directory, but I'm not sure what the fair use is around that. I figured it would be easier if I removed that external import and replaced it with a simple fetch request. Let me know if you disagree though!

Both works fine with me 🙂

2021-01-11 17:41 UTC, TorstenDittmann requested changes
Just remove the `deno/code.tar.gz` file and it is good to go! 🥳

2021-01-11 18:46 UTC, TorstenDittmann approved these changes

2021-02-04 08:34 UTC, Glide7 commented
@TorstenDittmann how can we move with this? :)

2021-02-04 09:00 UTC, TorstenDittmann commented
@eldadfux needs to merge this. I thought I tagged him back then 🤐

2021-02-10 08:40 UTC, Glide7 commented
@eldadfux reminder for this :)

2021-02-11 05:38 UTC, merged

2021-02-11 05:38 UTC, eldadfux commented
🚀