Add function to retrieve files from Appwrite storage and upload them …
appwrite/demos-for-functions pull request #301
Opened 2021-10-31 11:18 UTC by geryjuhasz

…to Dropbox

2021-10-31 18:30 UTC, geryjuhasz commented
<img width="1564" alt="out" src="https://user-images.githubusercontent.com/4499900/139596916-dfaadacf-6a93-42ba-9d1b-23e8247c552f.png">

<img width="1775" alt="logs" src="https://user-images.githubusercontent.com/4499900/139596918-d24c4bd4-8415-441b-b3db-289bc1bcb640.png">

<img width="1576" alt="db" src="https://user-images.githubusercontent.com/4499900/139596924-8fbf2591-fa0a-4997-8bdc-4405a57e9d59.png">

2021-11-28 18:20 UTC, christyjacob4 requested changes
Please address the comments

2021-11-28 18:20 UTC, christyjacob4 commented on php/file-backup/README.md
> +* **APPWRITE_FUNCTION_PROJECT_ID** - AppWrite Project ID
```suggestion
```
you can remove this var. it's passed by default to the cloud function

2021-11-28 18:20 UTC, christyjacob4 commented on php/file-backup/README.md
> +* **APPWRITE_ENDPOINT** - AppWrite Domain
```suggestion
* **APPWRITE_ENDPOINT** - Appwrite Domain 
```

2021-11-28 18:20 UTC, christyjacob4 commented on php/file-backup/README.md
> +* **APPWRITE_API_KEY** - AppWrite API key
```suggestion
* **APPWRITE_API_KEY** - Appwrite API key
```

2021-11-28 18:20 UTC, christyjacob4 commented on php/file-backup/README.md
> +
You're missing the steps required to package this as a tarfile. Please take a look at the other examples to find how.

2021-11-28 18:20 UTC, christyjacob4 commented on php/file-backup/README.md
> +php index.php fileId1 fileId2 ...
The trigger section does not look right. Please refer to my comment from earlier https://github.com/appwrite/demos-for-functions/pull/244#discussion_r757902352

2021-12-19 18:42 UTC, christyjacob4 commented
@geryjuhasz  closing this PR for now . Feel free to reopen it / create a new one when you're ready to start working on it once again

2021-12-19 18:42 UTC, closed without merging