Implement backupToStorage appwrite function
appwrite/demos-for-functions pull request #304
Opened 2021-10-31 21:01 UTC by geryjuhasz

2021-10-31 21:05 UTC, geryjuhasz commented
<img width="1747" alt="out" src="https://user-images.githubusercontent.com/4499900/139601203-bbaab65a-de6f-4cce-a6a1-34c8de00977a.png">

<img width="1774" alt="logs" src="https://user-images.githubusercontent.com/4499900/139601208-6d104340-ba8e-462f-bd7b-24d93e9fa232.png">

<img width="1373" alt="storage" src="https://user-images.githubusercontent.com/4499900/139601210-38e5bee7-a930-4a6c-9558-faf415222db1.png">

2021-11-01 07:15 UTC, Meldiron requested changes
Left some comments.

2021-11-01 07:15 UTC, Meldiron commented on php/backup-collections/index.php
> +$collections = $db->listCollections();
Lets add pagination, this will only return 25 collections.

2021-11-01 07:15 UTC, Meldiron commented on php/backup-collections/index.php
> +	$appwriteDocuments = $db->listDocuments($collection['$id']);
Lets add pagination, this will only return 25 documents.

2021-11-01 07:15 UTC, Meldiron commented on php/backup-collections/index.php
> +		unset($document['$permissions']);
Can we make this optional using environment variable?

2021-11-01 07:15 UTC, Meldiron commented on php/backup-collections/README.md
> +```
In the trigger, let's explain how it can be executed: Using "execute now" button in Appwrite console or using `createExecution` in client/server-side SDKs.

2021-11-28 16:04 UTC, christyjacob4 commented
@geryjuhasz closing this PR for now since there has been no activity in quite a long time. Feel free to reopen it when you're ready to start working on it once again. 🙂

2021-11-28 16:04 UTC, closed without merging