feat: adding remaining python functions, removing unnecessary dependencies, standardizing env variables
appwrite/demos-for-functions pull request #54
Opened 2021-02-16 18:58 UTC by hack3r-0m

Relevant issues:
#19 #40

Testing:
tested `welcome-email` and `storage-cleaner` manually

2021-02-16 19:02 UTC, hack3r-0m commented
@Glide7 can you please mark it DWOC?

2021-02-18 11:32 UTC, christyjacob4 commented on python/welcome-email/README.md
> +Sends the welcome email to the newly registered users to the app according to the template provided.
```suggestion
A sample Python Cloud Function for sending a welcome email to a newly registered user.
```

2021-02-18 11:32 UTC, christyjacob4 commented on python/welcome-email/README.md
> +* **MAILGUN_DOMAIN** = Domain Name from Mailgun
```suggestion
* **MAILGUN_API_KEY** -  API Key for Mailgun
* **MAILGUN_DOMAIN** - Domain Name from Mailgun
```

2021-02-18 11:35 UTC, christyjacob4 commented on python/welcome-email/README.md
> +* Click 'Activate'
```suggestion
* Navigate to the Overview Tab of your Cloud Function > Deploy Tag
* Input the command that will run your function (in this case `python main.py`) as your entrypoint command
* Upload your tarfile 
* Click 'Activate'
```

2021-02-18 11:38 UTC, christyjacob4 commented on python/welcome-email/main.py
> +try:
Have you tested that this function actually works ? and were you able to get an email sent to your inbox? 
If so, a screenshot would help

2021-02-18 11:42 UTC, christyjacob4 commented on python/storage-cleaner/README.md
> +A sample .NET Cloud Function for deleting files that are older than XX days on a schedule.
```suggestion
A sample python Cloud Function for deleting files that are older than XX days on a schedule.
```

2021-02-18 11:45 UTC, christyjacob4 commented on python/storage-cleaner/README.md
> +* Click 'Activate'
```suggestion
* Navigate to the Overview Tab of your Cloud Function > Deploy Tag
* Input the command that will run your function (in this case `python main.py`) as your entrypoint command
* Upload your tarfile 
* Click 'Activate'
```

2021-02-18 11:48 UTC, christyjacob4 requested changes
Please address the comments

2021-02-18 12:12 UTC, hack3r-0m commented on python/welcome-email/main.py
> +try:
![image](https://user-images.githubusercontent.com/54898623/108355342-b5cbaf00-7210-11eb-943a-0c8215bac320.png)

2021-02-18 12:15 UTC, hack3r-0m commented on python/welcome-email/main.py
> +try:
![image](https://user-images.githubusercontent.com/54898623/108355589-07743980-7211-11eb-9ed9-dadbaf40aff9.png)

2021-02-18 16:08 UTC, christyjacob4 commented on python/welcome-email/main.py
> +try:
Perfect ❤️

2021-02-18 16:09 UTC, christyjacob4 approved these changes
Awesome Work!!!! 👍

2021-02-18 16:15 UTC, merged

2021-02-18 16:15 UTC, eldadfux commented
🚀