Kotlin welcome email example
appwrite/demos-for-functions pull request #66
Opened 2021-06-23 20:17 UTC by christyjacob4

2021-06-25 07:37 UTC, lohanidamodar requested changes
Some white space issues. Rest LGTM

2021-06-25 07:37 UTC, lohanidamodar commented on kotlin/welcome-email/README.md
> +A sample Kotlin Cloud Function for sending a welcome email to a newly registered user.
For consistency new line after heading seems good

2021-06-25 07:37 UTC, lohanidamodar commented on kotlin/welcome-email/README.md
> +## 📝 Environment Variables
newline after headings

2021-06-25 07:37 UTC, lohanidamodar commented on kotlin/welcome-email/README.md
> +* Build a jar for the project. Here's a [Stack Overflow answer](https://stackoverflow.com/questions/1082580/how-to-build-jars-from-intellij-properly) to help you.
Isn't there simple steps?

2021-06-25 09:05 UTC, christyjacob4 commented on kotlin/welcome-email/README.md
> +* Build a jar for the project. Here's a [Stack Overflow answer](https://stackoverflow.com/questions/1082580/how-to-build-jars-from-intellij-properly) to help you.
This is the way to configure and build jars.
I have explained the steps in the written tutorial. I just wanted to keep the README concise.

2021-06-25 09:08 UTC, christyjacob4 commented on kotlin/welcome-email/README.md
> +A sample Kotlin Cloud Function for sending a welcome email to a newly registered user.
Done :+1:

2021-06-25 09:08 UTC, christyjacob4 commented on kotlin/welcome-email/README.md
> +## 📝 Environment Variables
Done :+1:

2021-06-25 09:47 UTC, lohanidamodar approved these changes

2021-06-25 09:47 UTC, lohanidamodar commented on kotlin/welcome-email/README.md
> +* Build a jar for the project. Here's a [Stack Overflow answer](https://stackoverflow.com/questions/1082580/how-to-build-jars-from-intellij-properly) to help you.
Ok

2021-06-30 08:41 UTC, abnegate approved these changes

2021-07-06 18:06 UTC, merged