Feat add fcm push notification sample to dotnet
appwrite/demos-for-functions pull request #72
Opened 2021-07-11 12:10 UTC by Miksier

Hello,

This PR adds a sample for FCM push notification sending. The sample uses official FCM lib for c#. Some setup is also needed other than just uploading the func but I hope the instructions are clear. 

Please let me know if something needs to be polished :)

2021-07-12 07:50 UTC, TorstenDittmann commented on dotnet/fcm-push-notifications/Program.cs
> +                //Token = "d8sG......OApP3"// token taken from FirebaseMessaging.instance.getToken()
Is this an API key?

If yes, lets add them via Environment Variables 👍🏻  You can access them via `Environment.GetEnvironmentVariable("ENV_VARIABLE")`.

2021-07-12 08:01 UTC, Miksier commented on dotnet/fcm-push-notifications/Program.cs
> +                //Token = "d8sG......OApP3"// token taken from FirebaseMessaging.instance.getToken()
Ah no, this is the token/string that gets paired to mobile device on registration with FCM. 
But yeah, I can add it as env. 
@TorstenDittmann or would it be better to use "Custom data" to show using the custom data env variable? I think I didnt saw it in samples and its a good occasion for it

2021-07-12 08:10 UTC, TorstenDittmann commented on dotnet/fcm-push-notifications/Program.cs
> +                //Token = "d8sG......OApP3"// token taken from FirebaseMessaging.instance.getToken()
Depends, usually this should also happen without user interaction. So getting the token from the Database or User's preferences is a good thing with this case 👍🏻

2021-07-12 08:10 UTC, TorstenDittmann approved these changes

2021-07-12 10:32 UTC, lohanidamodar requested changes
Everything is good. Just a white space for consistency.

2021-07-12 10:32 UTC, lohanidamodar commented on dotnet/fcm-push-notifications/README.md
> +* Ensure that your output looks like this
```suggestion
* Ensure that your output looks like this 

```
Just a line break before code block

2021-07-12 10:34 UTC, Miksier commented on dotnet/fcm-push-notifications/README.md
> +* Ensure that your output looks like this
ok, Ill take care of it later today when I get access to my pc ;)

2021-07-12 17:08 UTC, Miksier commented
K, think everything is good ;)

2021-07-13 12:52 UTC, merged

2021-07-13 12:53 UTC, TorstenDittmann commented
Thanks for the contribution 🙌🏻